# Generated by Django 3.0 on 2020-11-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_username', models.CharField(max_length=100)),
                ('employee_firstname', models.CharField(max_length=100)),
            ],
        ),
    ]
